packages:
  - 'packages/*'
  - 'examples/*'
  - 'extensions/*'
  - 'benchmarks'
  - 'e2e'

catalog:
  '@rslib/core': ^0.22.0
  '@rspress/core': ^2.0.14
  '@typescript/native-preview': 7.0.0-dev.20260609.1
  es-toolkit: ^1.47.0
  ts-pattern: ^5.9.0
  type-fest: ^5.7.0
  typescript: ^6.0.3
  vitest: ^4.1.8
  zod: ^4.4.3
