import { defineConfig } from 'ciderpress'

export default defineConfig({
  title: 'Platform Docs',
  description: 'Internal Engineering Documentation',
  theme: { themes: ['midnight'] },
  home: {
    hero: {
      tagline: 'Everything you need to build, ship, and scale.',
    },
    blocks: [
      { type: 'features', truncate: { description: 2 } },
      { type: 'showcase', columns: 2, truncate: { title: 1, description: 2 } },
    ],
  },
  apps: [
    {
      title: 'API',
      icon: 'logos:hono',
      description: 'Hono REST API with typed routes',
      tags: ['hono', 'typescript'],
      path: '/apps/api',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Console',
      icon: 'devicon:nextjs',
      description: 'Next.js dashboard',
      tags: ['nextjs', 'react'],
      path: '/apps/console',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Tasks',
      icon: 'simple-icons:triggerdotdev',
      description: 'Background job processing',
      tags: ['trigger.dev', 'async'],
      path: '/apps/tasks',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Workers',
      icon: 'logos:cloudflare-workers-icon',
      description: 'Edge worker functions',
      tags: ['cloudflare', 'edge'],
      path: '/apps/workers',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Gateway',
      icon: 'pixelarticons:server',
      description: 'API gateway and routing',
      tags: ['gateway', 'routing'],
      path: '/apps/gateway',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Scheduler',
      icon: 'pixelarticons:clock',
      description: 'Cron jobs and scheduled tasks',
      tags: ['cron', 'scheduler'],
      path: '/apps/scheduler',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Notifications',
      icon: 'pixelarticons:notification',
      description: 'Push, email, and in-app notifications',
      tags: ['notifications', 'email'],
      path: '/apps/notifications',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Analytics',
      icon: 'pixelarticons:chart',
      description: 'Usage tracking and metrics',
      tags: ['analytics', 'metrics'],
      path: '/apps/analytics',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
  ],
  packages: [
    {
      title: 'Database',
      icon: 'devicon:prisma',
      description: 'Prisma ORM schema and queries',
      tags: ['prisma', 'postgresql'],
      path: '/libs/database',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'AI',
      icon: 'pixelarticons:android',
      description: 'Agent framework with tools and workflows',
      tags: ['ai-sdk', 'agents'],
      path: '/libs/ai',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'FP',
      icon: 'pixelarticons:function',
      description: 'Functional programming utilities',
      tags: ['fp', 'utilities'],
      path: '/libs/fp',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Shell',
      icon: 'pixelarticons:terminal',
      description: 'Type-safe shell command SDK',
      tags: ['cli', 'codegen'],
      path: '/libs/shell',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Scout',
      icon: 'pixelarticons:search',
      description: 'Documentation intelligence and scanning',
      tags: ['scanning', 'classification'],
      path: '/libs/scout',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Config',
      icon: 'devicon:typescript',
      description: 'Shared configuration and env vars',
      tags: ['typescript'],
      path: '/libs/config',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Auth',
      icon: 'pixelarticons:lock',
      description: 'Authentication and session management',
      tags: ['auth', 'jwt'],
      path: '/libs/auth',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Cache',
      icon: 'pixelarticons:speed-fast',
      description: 'Caching layer with Redis backend',
      tags: ['redis', 'cache'],
      path: '/libs/cache',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Logger',
      icon: 'pixelarticons:article',
      description: 'Structured logging and observability',
      tags: ['logging', 'observability'],
      path: '/libs/logger',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Queue',
      icon: 'pixelarticons:list-box',
      description: 'Message queue abstractions',
      tags: ['queue', 'async'],
      path: '/libs/queue',
      include: 'docs/*.md',
      discover: { sort: 'alpha' },
    },
  ],
  pages: [
    {
      title: 'Getting Started',
      icon: 'pixelarticons:open',
      pages: [
        {
          title: 'Introduction',
          path: '/introduction',
          include: 'docs/README.md',
        },
        {
          title: 'Architecture',
          path: '/architecture',
          include: 'docs/architecture.md',
        },
        {
          title: 'Repository Structure',
          path: '/structure',
          include: 'docs/structure.md',
        },
        { title: 'Commands', path: '/commands', include: 'docs/commands.md' },
      ],
    },
    {
      title: 'Guides',
      icon: 'pixelarticons:article',
      path: '/guides',
      include: 'docs/guides/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Concepts',
      icon: 'pixelarticons:label',
      path: '/concepts',
      include: 'docs/concepts/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'AI',
      icon: 'pixelarticons:mood-happy',
      path: '/ai',
      pages: [
        {
          title: 'Overview',
          path: '/ai/overview',
          include: 'docs/ai/overview.md',
        },
        {
          title: 'Best Practices',
          path: '/ai/best-practices',
          include: 'docs/ai/best-practices/*.md',
          discover: { sort: 'alpha' },
        },
        {
          title: 'Coding Agents',
          path: '/ai/coding-agents',
          include: 'docs/ai/coding-agents/*.md',
          discover: { sort: 'alpha' },
        },
        {
          title: 'Concepts',
          path: '/ai/concepts',
          include: 'docs/ai/concepts/*.md',
          discover: { sort: 'alpha' },
        },
        {
          title: 'Ecosystem',
          path: '/ai/ecosystem',
          include: 'docs/ai/ecosystem/*.md',
          discover: { sort: 'alpha' },
        },
      ],
    },
    {
      title: 'Development',
      icon: 'pixelarticons:android',
      path: '/development',
      pages: [
        {
          title: 'Overview',
          path: '/development/overview',
          include: 'docs/development/overview.md',
        },
        {
          title: 'Standards',
          path: '/development/standards',
          include: 'docs/development/standards/*.md',
          discover: { sort: 'alpha' },
        },
        {
          title: 'Tools',
          path: '/development/tools',
          include: 'docs/development/tools/*.md',
          discover: { sort: 'alpha' },
        },
      ],
    },
    {
      title: 'Security',
      icon: 'pixelarticons:lock',
      path: '/security',
      include: 'docs/security/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Troubleshooting',
      icon: 'pixelarticons:alert',
      path: '/troubleshooting',
      include: 'docs/troubleshooting/*.md',
      discover: { sort: 'alpha' },
    },
    {
      title: 'Contributing',
      icon: 'pixelarticons:git-merge',
      pages: [
        {
          title: 'Overview',
          path: '/contributing',
          include: 'contributing/README.md',
        },
        {
          title: { from: 'frontmatter' },
          path: '/contributing/guides',
          include: 'contributing/guides/*.md',
          discover: { sort: 'alpha' },
        },
      ],
    },
  ],
  topbar: {
    nav: [
      { title: 'Getting Started', link: '/introduction' },
      {
        title: 'Docs',
        items: [
          { title: 'Guides', link: '/guides' },
          { title: 'Concepts', link: '/concepts' },
          { title: 'Architecture', link: '/architecture' },
          { title: 'Commands', link: '/commands' },
          { title: 'Structure', link: '/structure' },
        ],
      },
      {
        title: 'AI',
        items: [
          { title: 'Overview', link: '/ai/overview' },
          { title: 'Best Practices', link: '/ai/best-practices' },
          { title: 'Coding Agents', link: '/ai/coding-agents' },
          { title: 'Concepts', link: '/ai/concepts' },
          { title: 'Ecosystem', link: '/ai/ecosystem' },
        ],
      },
      {
        title: 'Workspace',
        items: [
          { title: 'API', link: '/apps/api' },
          { title: 'Console', link: '/apps/console' },
          { title: 'Workers', link: '/apps/workers' },
          { title: 'Database', link: '/libs/database' },
          { title: 'AI Library', link: '/libs/ai' },
          { title: 'Auth', link: '/libs/auth' },
        ],
      },
      {
        title: 'Operations',
        items: [
          { title: 'Development', link: '/development/overview' },
          { title: 'Standards', link: '/development/standards' },
          { title: 'Tools', link: '/development/tools' },
          { title: 'Security', link: '/security' },
          { title: 'Troubleshooting', link: '/troubleshooting' },
        ],
      },
    ],
  },
  socials: [{ icon: 'github', url: 'https://github.com/acme' }],
  footer: {
    message: 'Built with ciderpress',
    copyright: { company: 'Acme Inc.' },
  },
})
