export {
  SOCIAL_LINK_ICONS,
  defineConfig,
  defineTheme,
  hasGlobChars,
  resolveIcon,
  resolveOptionalIcon,
  serializeIcon,
} from '@ciderpress/config'
export { CiderpressLogo } from '@ciderpress/ui'
export type { CiderpressLogoProps } from '@ciderpress/ui'

export type {
  CiderpressConfig,
  Page,
  Feature,
  Workspace,
  WorkspaceGroup,
  Frontmatter,
  NavItem,
  CardConfig,
  ButtonConfig,
  BrandConfig,
  BannerConfig,
  BannerFn,
  TopbarConfig,
  SidebarConfig,
  SidebarPromo,
  FooterConfig,
  FooterColumn,
  CopyrightConfig,
  EditLinkConfig,
  ReportLinkConfig,
  DiscoverConfig,
  ResolvedPage,
  ResolvedSection,
  Result,
  TitleConfig,
  SortStrategy,
  HomeConfig,
  HomeHeroConfig,
  HomeProofConfig,
  HomeFeaturesConfig,
  HomeShowcaseConfig,
  HomeSplitConfig,
  HomeSplitVisual,
  HomeSplitVisualCode,
  HomeSplitVisualImage,
  HomeCtaConfig,
  HomeHeroDemoConfig,
  HomeHeroDemoImage,
  HomeHeroDemoTerminal,
  HomeHeroDemoLine,
  HomeSectionHeading,
  HomeBlock,
  HomeBlockType,
  HomeProofBlock,
  HomeFeaturesBlock,
  HomeShowcaseBlock,
  HomeSplitBlock,
  HomeCtaBlock,
  TruncateConfig,
  AnnouncementConfig,
  SocialLink,
  SocialLinkIcon,
  OpenAPISpec,
  IconConfig,
  IconImage,
  IconColor,
  IconId,
  IconPrefix,
  ImageSource,
  LoaderConfig,
  LoaderStaticConfig,
  LoaderComponentConfig,
  LogoConfig,
  LogoContext,
  LogoFn,
  LogoImage,
  ThemeSettings,
  ThemeEntry,
  ResolvedIcon,
  ResolvedIconifyIcon,
  ResolvedImageIcon,
  SerializedIcon,
} from '@ciderpress/config'

export type {
  CiderpressTheme,
  CiderpressThemeInput,
  CiderpressThemeInputVariants,
  CiderpressTokens,
  ThemeVariant,
  ThemeVariantTokens,
  ThemeName,
  ThemeColors,
  BuiltInThemeName,
  BuiltInIconColor,
} from '@ciderpress/theme'

export type { LoadConfigOptions } from '@ciderpress/config'
